version: 0.2

phases:
  install:
    commands:
      - echo Installing Java 17 and SonarScanner...
      - apt-get update && apt-get install -y openjdk-17-jre # Install Java 17
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner.zip -d /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin

  pre_build:
    commands:
      - echo Starting SonarCloud analysis...
      - sleep 5  # Optional: Wait for 5 seconds before proceeding

  build:
    commands:
      - echo Running SonarCloud analysis...
      - sonar-scanner -X -Dsonar.organization=isaacbrownn -Dsonar.projectKey=Isaacbrownn_SONAR -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=aedbc73ac39c1f6003dcfd993ff7d9bb46f22ae54
      - sleep 5  # Optional: Wait for 5 seconds after running the analysis

artifacts:
  files:
    - '**/*'
  discard-paths: yes
