version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting SonarCloud analysis...
      - sleep 5  # Optional: Wait for 5 seconds before proceeding

  build:
    commands:
      - echo Running SonarCloud analysis...
      - sonar-scanner -X -Dsonar.organization=isaacbrownn -Dsonar.projectKey=Isaacbrownn_SONAR -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=aedbc73ac39c1f6003dcfd993ff7d9bb46f22ae54
      - sleep 5  # Optional: Wait for 5 seconds after running the analysis

artifacts:
  files:
    - '**/*'
  discard-paths: yes
