version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Keep Node.js version as is
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip  # Updated to a compatible version
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner-cli

  build:
    commands:
      - echo Logging in to SonarCloud..... 
      - ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -X --define sonar.organization=isaacbrownn --define sonar.projectKey=Isaacbrownn_SONAR  --define sonar.host.url=https://sonarcloud.io --define sonar.token=6afb9f9bdf23103c6c38c12300ceea40001d2ae2
      - cat analysis.json
       post build:
    commands:
      - echo Building Project
      - echo Finished Building

cache:
  paths:
    - "node_modules/**/*"
