version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Ensure you're using Java 17
    commands:
      - echo "Installing dependencies..."
      - mvn install # Adjust if you're using a different build tool
  pre_build:
    commands:
      - echo "Running SonarCloud analysis..."
  build:
    commands:
      - echo "Building the project..."
      - mvn package # Adjust if you're using a different build tool
      - echo "Running SonarCloud scanner..."
      - sonar-scanner -X -Dsonar.organization=isaacbrownn -Dsonar.projectKey=Isaacbrownn_SONAR -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN # Use environment variable for security
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - target/*.jar # Adjust based on the output of your build

env:
  variables:
    SONAR_TOKEN: "aedbc73ac39c1f6003dcfd993ff7d9bb46f22ae54" # You may want to set this in the AWS CodeBuild environment variables instead
